### ISSUE TITLE
Integration of Actor System into Python FL Stack

### ISSUE THREAD

**Issue by ayush268** [NimbleEdge/RecoEdge#110]
- [ ] FLSystemManager Actor Completion
    - [ ] Fix and Add State Variables in the FLSystemManager Actor Behavior Class https://github.com/NimbleEdge/RecoEdge/blob/75c397a4d911cbea04f2c2913a95ccc8642d5bb6/scala_core/src/main/scala/org/nimbleedge/recoedge/FLSystemManager.scala#L64
    - [ ] Implement Start Cycle Message and Method https://github.com/NimbleEdge/RecoEdge/blob/75c397a4d911cbea04f2c2913a95ccc8642d5bb6/scala_core/src/main/scala/org/nimbleedge/recoedge/FLSystemManager.scala#L53
    - [ ] Add more messages (methods) in FLSystemManager Actor https://github.com/NimbleEdge/RecoEdge/blob/75c397a4d911cbea04f2c2913a95ccc8642d5bb6/scala_core/src/main/scala/org/nimbleedge/recoedge/FLSystemManager.scala#L57
    - [ ] Take care of the case when Orchestrator Gets Terminated https://github.com/NimbleEdge/RecoEdge/blob/75c397a4d911cbea04f2c2913a95ccc8642d5bb6/scala_core/src/main/scala/org/nimbleedge/recoedge/FLSystemManager.scala#L125

- [ ] Orchestrator Actor Completion
    - [ ] Fix and Add State Variables in the Orchestrator Actor Behavior Class https://github.com/NimbleEdge/RecoEdge/blob/75c397a4d911cbea04f2c2913a95ccc8642d5bb6/scala_core/src/main/scala/org/nimbleedge/recoedge/Orchestrator.scala#L33
    - [ ] Add more messages (methods) in Orchestrator Actor https://github.com/NimbleEdge/RecoEdge/blob/75c397a4d911cbea04f2c2913a95ccc8642d5bb6/scala_core/src/main/scala/org/nimbleedge/recoedge/Orchestrator.scala#L25
    - [ ] Take care of the case when Aggregator Gets Terminated https://github.com/NimbleEdge/RecoEdge/blob/75c397a4d911cbea04f2c2913a95ccc8642d5bb6/scala_core/src/main/scala/org/nimbleedge/recoedge/Orchestrator.scala#L106

- [ ] Aggregator Actor Completion
    - [ ] Fix and Add State Variables in the Aggregator Actor Behavior Class https://github.com/NimbleEdge/RecoEdge/blob/75c397a4d911cbea04f2c2913a95ccc8642d5bb6/scala_core/src/main/scala/org/nimbleedge/recoedge/Aggregator.scala#L36
    - [ ] Add more messages (methods) in Aggregator Actor https://github.com/NimbleEdge/RecoEdge/blob/75c397a4d911cbea04f2c2913a95ccc8642d5bb6/scala_core/src/main/scala/org/nimbleedge/recoedge/Aggregator.scala#L28
    - [ ] Take care of the case when child Aggregator Gets Terminated https://github.com/NimbleEdge/RecoEdge/blob/75c397a4d911cbea04f2c2913a95ccc8642d5bb6/scala_core/src/main/scala/org/nimbleedge/recoedge/Aggregator.scala#L155
    - [ ] Take care of the case when child Trainer Gets Terminated https://github.com/NimbleEdge/RecoEdge/blob/75c397a4d911cbea04f2c2913a95ccc8642d5bb6/scala_core/src/main/scala/org/nimbleedge/recoedge/Aggregator.scala#L160

- [ ] Trainer Actor Completion
    - [ ] Fix and Add State Variables in the Trainer Actor Behavior Class https://github.com/NimbleEdge/RecoEdge/blob/75c397a4d911cbea04f2c2913a95ccc8642d5bb6/scala_core/src/main/scala/org/nimbleedge/recoedge/Trainer.scala#L25
    - [ ] Add more messages (methods) in Aggregator Actor https://github.com/NimbleEdge/RecoEdge/blob/75c397a4d911cbea04f2c2913a95ccc8642d5bb6/scala_core/src/main/scala/org/nimbleedge/recoedge/Trainer.scala#L18
    - [ ] Implement Trainer Methods https://github.com/NimbleEdge/RecoEdge/blob/75c397a4d911cbea04f2c2913a95ccc8642d5bb6/scala_core/src/main/scala/org/nimbleedge/recoedge/Trainer.scala#L32
