### ISSUE TITLE
Integration Tasks

### ISSUE THREAD

**Issue by vkkhare** [NimbleEdge/RecoEdge#16]
- [x] Global Com Manager needs `handle_messages` (iterate over all the messages in the zeroMQ)
- [x] Communication Manager needs a dict of futures for awaiting on the receive method
- [x] Federated Worker has a method `send_message(msg)` which global com calls to put the msg in its asyncio Q
- [ ] Initiate global com stream on process 0
