### ISSUE TITLE
Model worker as an Actor

### ISSUE THREAD

**Issue by sidarth164** [NimbleEdge/RecoEdge#31]
## What
Decouple the worker execution from the actual business logic. This would allow us to avoid implementing worker co-routines.

## Objectives
- [ ] Identify worker states
- [ ] Add worker behaviors based on message received
- [ ] A behavior can change the worker state

## Tasks
- [ ] Define communications between different actors
- [ ] Implement Orchestrator actor
- [ ] Implement Aggregator actor
- [ ] Implement Trainer actor
- [ ] Implement Admin Panel actor
- [ ] Integrate all the components and do an end-to-end testing

## Epic
- #29
