### ISSUE TITLE
Process Manager Tasks

### ISSUE THREAD

**Issue by vkkhare** [NimbleEdge/RecoEdge#7]
Assume n aggregators and k trainers. 

- [x] Aggregator always starts a cycle by calling `get_model_updates()` from its neighbours.
- [x] All these requests are passed on to the global com manager and the aggregator suspends
- [x] The requests from communication interface passes onto Process Manager
- [x] Comm manager collates the receive requests and sends `neighbours_out` to the respective workers via the communication manager
- [x] Each worker on getting receiver request spins up its training process and submits a job to worker process pool (again process manager)
- [x] The process manager will receive thousands of train jobs (`k`) and it will batch them into num worker pool threads (`t`). 
- [x] Each process sequentially trains `k/t` workers and submits the model updates to the respective workers
- [x] The workers are awakened and their model persisted or sent depending upon available memory
